/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************/

//A program to turn the LED on using bit masking technique

#include <stdint.h>

int main(void)
{
    // Peripheral addresses

	uint32_t *pCLOCK_REG_AHB       = (uint32_t*) 0x40021014;
	uint32_t *pGPIOB_MODE_REG      = (uint32_t*) 0x48000400;
	uint32_t *pGPIOB_OUT_DATA_REG  = (uint32_t*) 0x48000414;


	//Enabling the clock for the GPIOB

	*pCLOCK_REG_AHB        |= 0x00040000;

	//Configuring the GPIOB as output mode (pin 13)
	//1. star by clearing the 26th and 27th bit.
	//2. then setting bit 26 as 1, since 27th is already 0;

	 *pGPIOB_MODE_REG      &=  0xF3FFFFFF; // clearing 0
     *pGPIOB_MODE_REG      |=  0x04000000; //setting   1

     //configuring the GPIOB as output data register, so we can write 1
     //to turn the LED on

     *pGPIOB_OUT_DATA_REG  |= 0x2000; //setting PB13 HIGH (LED ON)



    /* Loop forever */
	while(1);
}
